import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { loadExternalPlugins, validateExternalPlugin } from "../dist/src/core/application/externalPluginLoader.js";

function readNormalized(path) {
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

test("validates the v2 plugin contract", () => {
  const plugin = validateExternalPlugin({
    metadata: {
      name: "contract-plugin",
      version: "1.0.0",
      apiVersion: "2.0.0",
      language: "fixture",
      framework: "api"
    },
    capabilities: { entities: true, crud: true },
    generateProject: () => []
  });

  assert.equal(plugin.metadata.name, "contract-plugin");
  assert.equal(plugin.metadata.apiVersion, "2.0.0");
  assert.equal(plugin.capabilities?.crud, true);
});

test("loads a local v2 plugin and generates fixture output", () => {
  const outputRoot = mkdtempSync(join(tmpdir(), "arxgen-plugin-test-"));
  const pluginPath = join(outputRoot, "fixture-plugin.mjs");

  try {
    writeFileSync(pluginPath, `export default ({ apiVersion }) => ({
  metadata: {
    name: "fixture-stack",
    version: "1.0.0",
    apiVersion,
    language: "fixture",
    framework: "api"
  },
  capabilities: { entities: true, crud: true, validation: ["fixture"] },
  generateProject({ config, root, plugin }) {
    return [
      {
        path: \`\${root}/README.md\`,
        content: \`# \${config.projectName}\\n\\nGenerated by \${plugin.name}.\\n\`
      }
    ];
  },
  generateEntity({ root, entity }) {
    return [
      {
        path: \`\${root}/entities/\${entity.name}.txt\`,
        content: entity.fields.map((field) => \`\${field.name}:\${field.type}\`).join("\\n") + "\\n"
      }
    ];
  }
});`, "utf8");

    const listOutput = execFileSync(
      process.execPath,
      ["dist/bin/arxgen.js", "list", "plugins", "--plugin", pluginPath],
      { cwd: process.cwd(), stdio: "pipe", encoding: "utf8" }
    );
    assert.match(listOutput, /fixture-stack@1\.0\.0 \(fixture\/api\) API 2\.0\.0/);

    execFileSync(
      process.execPath,
      [
        "dist/bin/arxgen.js",
        "--plugin",
        pluginPath,
        "create",
        "--name",
        "fixture-api",
        "--language",
        "fixture",
        "--framework",
        "api",
        "--entity",
        "student",
        "--field",
        "name:string",
        "--out",
        outputRoot
      ],
      { cwd: process.cwd(), stdio: "pipe" }
    );

    const projectRoot = join(outputRoot, "fixture-api");
    assert.equal(existsSync(join(projectRoot, "README.md")), true);
    assert.equal(existsSync(join(projectRoot, "entities/student.txt")), true);
    assert.equal(
      readNormalized(join(projectRoot, "README.md")),
      readNormalized(join(process.cwd(), "tests", "snapshots", "plugin-fixture-readme.md.snap"))
    );
    assert.equal(readNormalized(join(projectRoot, "entities/student.txt")), "name:string\n");
  } finally {
    rmSync(outputRoot, { recursive: true, force: true });
  }
});

test("rejects incompatible external plugin API versions", async () => {
  const outputRoot = mkdtempSync(join(tmpdir(), "arxgen-plugin-test-"));
  const pluginPath = join(outputRoot, "bad-plugin.mjs");

  try {
    writeFileSync(pluginPath, `export default {
  metadata: {
    name: "bad-plugin",
    version: "1.0.0",
    apiVersion: "1.0.0",
    language: "fixture",
    framework: "api"
  },
  generateProject() {
    return [];
  }
};`, "utf8");

    await assert.rejects(
      () => loadExternalPlugins([pluginPath]),
      /uses plugin API 1\.0\.0; arxgen supports 2\.0\.0/
    );
  } finally {
    rmSync(outputRoot, { recursive: true, force: true });
  }
});
