export default ({ apiVersion }) => ({
  metadata: {
    name: "example-stack",
    version: "1.0.0",
    apiVersion,
    language: "example",
    framework: "api",
    description: "Minimal arxgen v2 plugin example"
  },
  capabilities: {
    entities: true,
    crud: true,
    productionReady: false
  },
  generateProject({ config, root, plugin }) {
    return [
      {
        path: `${root}/README.md`,
        content: `# ${config.projectName}\n\nGenerated by ${plugin.name}.\n`
      }
    ];
  },
  generateEntity({ root, entity }) {
    return [
      {
        path: `${root}/entities/${entity.name}.txt`,
        content: entity.fields.map((field) => `${field.name}:${field.type}`).join("\n") + "\n"
      }
    ];
  }
});
